SerwisOgloszen/Controllers/KategoriaController.cs
using SerwisOgloszen.BazaDanych;
using SerwisOgloszen.Models;
using SerwisOgloszen.Repozytoria;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SerwisOgloszen.Controllers
{
    public class KategoriaController : Controller
    {
        // GET: Kategoria
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult ListaKategorii()
        {
            try
            {
                KategoriaRepozytorium kategoriaRepozytorium = new KategoriaRepozytorium();
                List<Kategoria> listaKategorii = kategoriaRepozytorium.PobierzWszystkie();
                return View(listaKategorii);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }
        [HttpGet]
        //[Authorize(Roles = "Administrator")]
        [Authorize]
        public ActionResult Zapisz(long? id)
        {
            try
            {
                ZapiszKategorieViewModel model = new ZapiszKategorieViewModel();

                if (id.HasValue) // to to samo co id != null
                {
                    KategoriaRepozytorium kategoriaRepozytorium = new KategoriaRepozytorium();
                    Kategoria pobraneKategorie = kategoriaRepozytorium.Pobierz(id.Value); //id.value pobiera wartosc z  typu ktory pozwala na null

                    model.Id = pobraneKategorie.Id;
                    model.Nazwa = pobraneKategorie.Nazwa;
                    model.CzyUsunieta = pobraneKategorie.CzyUsunieta;
                    // throw new Exception("ZLe");
                }
                return View("ZapiszKategorie", model);

            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Zapisz(ZapiszKategorieViewModel model)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    KategoriaRepozytorium kategoriaRepozytorium = new KategoriaRepozytorium();
                    Kategoria kategoria = null;
                    if (model.Id.HasValue == true)
                    {
                        kategoria = kategoriaRepozytorium.Pobierz(model.Id.Value);
                        kategoria.Nazwa = model.Nazwa;
                        kategoria.CzyUsunieta = model.CzyUsunieta;
                    }
                    else
                    {
                        kategoria = new Kategoria()
                        {
                            CzyUsunieta = model.CzyUsunieta,
                            Nazwa = model.Nazwa
                        };
                    }
                    long? rezultatZapisania = kategoriaRepozytorium.Zapisz(kategoria);
                    return RedirectToAction("ListaKategorii");
                }
                else
                {
                    return View("ZapiszKategorie", model);
                }
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Usun(long id)
        {
            try
            {
                KategoriaRepozytorium kategoriaRepozytorium = new KategoriaRepozytorium();
                bool rezultatUsuniecia = kategoriaRepozytorium.UsunKategorie(id);
                return RedirectToAction("ListaKategorii");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

    }
}

SerwisOgloszen/Controllers/WiadomoscController.cs
using SerwisOgloszen.BazaDanych;
using SerwisOgloszen.Models;
using SerwisOgloszen.Repozytoria;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace SerwisOgloszen.Controllers
{
    public class WiadomoscController : Controller
    {

        [HttpGet]
        [Authorize]
        public ActionResult ListaKonwersacji()
        {
            try
            {
                WiadomoscRepozytorium wiadomoscRepozytorium = new WiadomoscRepozytorium();
                List<Wiadomosc> listaWiadomosci = wiadomoscRepozytorium.PobierzWszystkie(((Uzytkownik)Session["uzytkownik"]).Id);
                List<ListaKonwersacjiViewModel> konwersacjaViewModel = new List<ListaKonwersacjiViewModel>();
                foreach (Wiadomosc wiadomosc in listaWiadomosci)
                {
                    long uzytkownikId = wiadomosc.OdbierajacyUzytkownikId;
                    string loginUzytkownika = wiadomosc.UzytkownikOdbierajacy.Login;
                    if (uzytkownikId == ((Uzytkownik)Session["uzytkownik"]).Id)
                    {
                        uzytkownikId = wiadomosc.WysylajacyUzytkownikId;
                        loginUzytkownika = wiadomosc.UzytkownikWysylajacy.Login;
                    }
                    if (konwersacjaViewModel.Where(x => x.OgloszenieId == wiadomosc.OgloszenieId
                        && x.UzytkownikId == uzytkownikId).Any() == false)
                    {
                        konwersacjaViewModel.Add(new ListaKonwersacjiViewModel()
                        {
                            DataOstatniejWiadomosci = wiadomosc.DataDodania,
                            LoginUzytkownika = loginUzytkownika,
                            OgloszenieId = wiadomosc.OgloszenieId,
                            TematOgloszenia = wiadomosc.Ogloszenie.Temat,
                            UzytkownikId = uzytkownikId,
                            IloscWiadomosci = listaWiadomosci.Where(x => x.OgloszenieId == wiadomosc.OgloszenieId
                                && (x.WysylajacyUzytkownikId == uzytkownikId || x.OdbierajacyUzytkownikId == uzytkownikId)).Count()
                        });
                    }
                }
                return View(konwersacjaViewModel);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpGet]
        [Authorize]
        public ActionResult WyslijWiadomosc(long ogloszenieId, long odbierajacyUzytkownikId) //ten parametre biore z actioon link
        {
            try
            {
                WiadomoscRepozytorium wiadomoscRepozytorium = new WiadomoscRepozytorium();
                OgloszenieRepozytorium ogloszenieRepozytorium = new OgloszenieRepozytorium();
                Ogloszenie ogloszenie = ogloszenieRepozytorium.Pobierz(ogloszenieId);
                List<Wiadomosc> listaWiadomosci = wiadomoscRepozytorium.Pobierz(((Uzytkownik)Session["uzytkownik"]).Id, odbierajacyUzytkownikId, ogloszenie.Id);// pobiera wszystkie z 3 parametrami ma byc 
                SzczegolyKonwersacjiViewModel szczegolyKonwersacjiViewModel = new SzczegolyKonwersacjiViewModel();
                szczegolyKonwersacjiViewModel.ListaWiadomosci = listaWiadomosci;
                szczegolyKonwersacjiViewModel.Ogloszenie = ogloszenie;
                szczegolyKonwersacjiViewModel.OdbierajacyUzytkownikId = odbierajacyUzytkownikId;
                szczegolyKonwersacjiViewModel.OgloszenieId = ogloszenieId;
                return View("SzczegolyKonwersacji", szczegolyKonwersacjiViewModel);
            }
            catch (Exception ex)
            {
                return View("ListaOgloszen2", "Ogloszenie");
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult WyslijWiadomosc(SzczegolyKonwersacjiViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    WiadomoscRepozytorium wiadomoscRepozytorium = new WiadomoscRepozytorium();
                    Wiadomosc wiadomosc = new Wiadomosc();
                    wiadomosc.Tresc = model.Tresc;
                    wiadomosc.OdbierajacyUzytkownikId = model.OdbierajacyUzytkownikId;
                    wiadomosc.OgloszenieId = model.OgloszenieId;
                    wiadomosc.DataDodania = DateTime.Now;
                    wiadomosc.WysylajacyUzytkownikId = ((Uzytkownik)Session["uzytkownik"]).Id;
                    wiadomoscRepozytorium.Zapisz(wiadomosc);
                    return RedirectToAction("WyslijWiadomosc", new
                    {
                        ogloszenieId = model.OgloszenieId,
                        odbierajacyUzytkownikId = model.OdbierajacyUzytkownikId
                    });
                }
                else
                {
                    return RedirectToAction("WyslijWiadomosc", new
                    {
                        ogloszenieId = model.OgloszenieId,
                        odbierajacyUzytkownikId = model.OdbierajacyUzytkownikId
                    });
                }
            }
            catch
            {
                return View("Error");

            }
        }
    }
}

SerwisOgloszen/Views/Shared/_Layout.cshtml
@using SerwisOgloszen.Enums;
@using SerwisOgloszen.BazaDanych;
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Serwis ogłoszeń</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/js")
    @RenderSection("scripts", required: false)

    <script>
        $.validator.setDefaults({
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            },
            errorElement: 'span',
            errorClass: 'help-block',
            errorPlacement: function (error, element) {
                if (element.parent('.input-group').length) {
                    error.insertAfter(element.parent());
                } else {
                    error.insertAfter(element);
                }
            }
        });


        $(document).ready(function () {
            autosize($('textarea'));
            $('#link-wyloguj').click(function () {
                $('#form-wyloguj').submit();
            });
        });

    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Serwis ogłoszeń", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    @*<li>@Html.ActionLink("Stare ogłoszenia", "ListaOgloszen", "Ogloszenie")</li>*@
                    <li>@Html.ActionLink("Lista ogłoszeń", "ListaOgloszen2", "Ogloszenie")</li>
                    @if (Request.IsAuthenticated == true && (RolaUzytkownika)((Uzytkownik)Session["uzytkownik"]).Rola == RolaUzytkownika.Administrator)
                    {
                        <li>
                            @Html.ActionLink("Lista Użytkowników", "ListaUzytkownikow", "Uzytkownik")
                        </li>
                            <li>
                                @Html.ActionLink("Wiadomości", "ListaKonwersacji", "Wiadomosc")
                            </li>
                            <li>
                                @Html.ActionLink("Lista kategorii", "ListaKategorii", "Kategoria")
                            </li>

                    }
                    else if (Request.IsAuthenticated == true)
                    {
                        <li>
                            @Html.ActionLink("Wiadomości", "ListaKonwersacji", "Wiadomosc");
                        </li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @if (Request.IsAuthenticated == false)
                        {
                        <li>@Html.ActionLink("Zaloguj", "Zaloguj", "Uzytkownik")</li>
                        <li>@Html.ActionLink("Zarejestruj", "Zarejestruj", "Uzytkownik")</li>

                        }
                        else
                        {
                            <li>
                                <a id="link-wyloguj" href="#">Wyloguj</a>
                                @using (Html.BeginForm("Wyloguj", "Uzytkownik", FormMethod.Post, new { id = "form-wyloguj" }))
                                {

                                }
                            </li>
                            <li>
                                <a>@User.Identity.Name</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year — Serwis ogłoszeń</p>
                @*@User.Identity.Name
                    @(((SerwisOgloszen.BazaDanych.Uzytkownik)Session["uzytkownik"]).Id)*@
            </footer>
        </div>
    </body>
</html>