SerwisOgloszen/Models/EdytujViewModel.cs
using SerwisOgloszen.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SerwisOgloszen.Models
{
    public class EdytujViewModel
    {
        public long Id { get; set; }

        [Display(Name = "Hasło")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "Niepoprawna ilość znaków")]
        public string Haslo { get; set; }

        [System.ComponentModel.DataAnnotations.Compare("Haslo", ErrorMessage = "Niezgodne hasła")]
        [Display(Name = "Powtórz hasło")]
        public string PowtorzoneHaslo { get; set; }

        public RolaUzytkownika Rola { get; set; }

        public List<SelectListItem> ListaRol { get; set; }

        public string Login { get; set; }

        public EdytujViewModel()
        {
            ListaRol = new List<SelectListItem>();
            ListaRol.Add(new SelectListItem()
            {
                Text=RolaUzytkownika.Administrator.ToString(), /* wchodze w enuma pobieram z niego wartos i robie to string bo tego wymaga*/
                Value=((byte)RolaUzytkownika.Administrator).ToString()  /*tu musialem dac typ byte bo w bazie jest tinyint a pozniej dac to string*/
            });
            ListaRol.Add(new SelectListItem()
            {
                Text = RolaUzytkownika.Uzytkownik.ToString(), /* wchodze w enuma pobieram z niego wartos i robie to string bo tego wymaga*/
                Value = ((byte)RolaUzytkownika.Uzytkownik).ToString()  /*tu musialem dac typ byte bo w bazie jest tinyint a pozniej dac to string*/
            });
        }
    }
}

SerwisOgloszen/Models/LogowanieViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SerwisOgloszen.Models
{
    public class LogowanieViewModel
    {
        //[Display(Name ="Twój Login")]
        [Required(ErrorMessage = "Pole wymagane")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "Niepoprawna ilość znaków")]
       /* [Compare("Haslo")] *//*sluzy np do porownywania hasel przy rejestracji*/
        public string Login { get; set; }

        [Required(ErrorMessage = "Pole wymagane")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "Niepoprawna ilość znaków")]
        [Display(Name ="Hasło")]
        public string Haslo { get; set; }

        [Display(Name ="Zapamiętaj mnie")]
        public bool ZapamietajMnie { get; set; }

    }
}

SerwisOgloszen/Models/RejestracjaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SerwisOgloszen.Models
{
    public class RejestracjaViewModel
    {

        [Required(ErrorMessage = "Pole wymagane")]
        [StringLength(20, MinimumLength = 4 ,ErrorMessage ="Niepoprawna ilość znaków")]
        public string Login { get; set; }

        [Display(Name = "Hasło")]
        [Required(ErrorMessage = "Pole wymagane")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "Niepoprawna ilość znaków")]
        public string Haslo { get; set; }

        [Compare("Haslo", ErrorMessage = "Niezgodne hasła")]
        [Display(Name = "Powtórz hasło")]
        [Required(ErrorMessage = "Pole wymagane")]
        public string PowtorzoneHaslo { get; set; }

    }
}

SerwisOgloszen/Controllers/UzytkownikController.cs
using SerwisOgloszen.BazaDanych;
using SerwisOgloszen.Enums;
using SerwisOgloszen.Models;
using SerwisOgloszen.Repozytoria;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using SerwisOgloszen.Helpers;
using System.Security.Claims;
using Microsoft.Owin.Security.OAuth;
using System.Threading.Tasks;

namespace SerwisOgloszen.Controllers
{
    public class UzytkownikController : Controller
    {
        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        // GET: Uzytkownik
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Anuluj()
        {
            try
            {
                UzytkownikRepozytorium uzytkownikRepozytorium = new UzytkownikRepozytorium();
                List<Uzytkownik> listaUzytkownikow = uzytkownikRepozytorium.PobierzWszystkich();
                return RedirectToAction("ListaUzytkownikow", listaUzytkownikow);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }
        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edytuj(long id)
        {
            try
            {
                UzytkownikRepozytorium uzytkownikRepozytorium = new UzytkownikRepozytorium();
                Uzytkownik uzytkownik = uzytkownikRepozytorium.Pobierz(id);
                EdytujViewModel edytujViewModel = new EdytujViewModel()
                {
                    Id = uzytkownik.Id,
                    Login = uzytkownik.Login,
                    Rola = (RolaUzytkownika)uzytkownik.Rola
                };

                return View(edytujViewModel);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edytuj(EdytujViewModel model)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    UzytkownikRepozytorium uzytkownikRepozytorium = new UzytkownikRepozytorium();
                    Uzytkownik uzytkownik = uzytkownikRepozytorium.Pobierz(model.Id);
                    uzytkownik.Rola = (byte)model.Rola;
                    if (string.IsNullOrEmpty(model.Haslo) == false)
                    {
                        uzytkownik.Haslo = model.Haslo;
                    }
                    long? rezultatEdycji = uzytkownikRepozytorium.Zapisz(uzytkownik);
                    if (rezultatEdycji != null)
                    {
                        return RedirectToAction("ListaUzytkownikow");
                    }
                    else
                    {
                        return View("Error");
                    }
                }
                else
                {
                    return View("Edytuj", model);
                }
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Usun(long id)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    UzytkownikRepozytorium uzytkownikRepozytorium = new UzytkownikRepozytorium();
                    bool rezultatUsuniecia = uzytkownikRepozytorium.Usun(id);
                    return RedirectToAction("ListaUzytkownikow");
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }
        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult ListaUzytkownikow()
        {
            try
            {
                UzytkownikRepozytorium uzytkownikRepozytorium = new UzytkownikRepozytorium();
                List<Uzytkownik> listaUzytkownikow = uzytkownikRepozytorium.PobierzWszystkich();
                return View("ListaUzytkownikow", listaUzytkownikow);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }



        [HttpGet]
        public ActionResult Zaloguj()
        {
            try
            {
                UzytkownikRepozytorium uzytkownikRepozytorium = new UzytkownikRepozytorium();
                List<Uzytkownik> listaUzytkownikow = uzytkownikRepozytorium.PobierzWszystkich();
                //throw new Exception(); wlasny wyjatek do sprawdzenia
                return View("Logowanie");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult Zaloguj(LogowanieViewModel model)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    var result = new ApplicationSignInManager(HttpContext.GetOwinContext()).PasswordSignIn(model);

                    switch (result)
                    {
                        case SignInStatus.Success:
                            var tokenExpiration = TimeSpan.FromDays(1);
                            ClaimsIdentity identity = new ClaimsIdentity(OAuthDefaults.AuthenticationType);
                            identity.AddClaim(new Claim(ClaimTypes.Name, model.Login));
                            var props = new AuthenticationProperties()
                            {
                                IssuedUtc = DateTime.UtcNow,
                                ExpiresUtc = DateTime.UtcNow.Add(tokenExpiration),
                            };
                            var ticket = new AuthenticationTicket(identity, props);
                            var accessToken = Startup.OAuthServerOptions.AccessTokenFormat.Protect(ticket);
                            HttpCookie ciasteczkoZTokenem = new HttpCookie("tokenOAuth", "Bearer " + accessToken);
                            Response.Cookies.Add(ciasteczkoZTokenem);


                            return RedirectToAction("ListaOgloszen2", "Ogloszenie");

                        case SignInStatus.LockedOut:
                        case SignInStatus.RequiresVerification:
                        case SignInStatus.Failure:
                        default:
                            ModelState.AddModelError("Haslo", "Niepoprawny login lub hasło");
                            return View("Logowanie", model);
                    }

                }
                else
                {
                    return View("Logowanie", model);
                }
            }
            catch (Exception ex)
            {
                return View("Error");
            }

        }

        //[HttpPost]
        //[AllowAnonymous]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> ExternalLoginConfirmation(ExternalLoginConfirmationViewModel model, string returnUrl)
        //{
        //    if (User.Identity.IsAuthenticated)
        //    {
        //        return RedirectToAction("Index", "Manage");
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        // Get the information about the user from the external login provider
        //        var info = await AuthenticationManager.GetExternalLoginInfoAsync();
        //        if (info == null)
        //        {
        //            return View("ExternalLoginFailure");
        //        }
        //        var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
        //        var result = await UserManager.CreateAsync(user);
        //        if (result.Succeeded)
        //        {
        //            result = await UserManager.AddLoginAsync(user.Id, info.Login);
        //            if (result.Succeeded)
        //            {
        //                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
        //                return RedirectToLocal(returnUrl);
        //            }
        //        }
        //        AddErrors(result);
        //    }

        //    ViewBag.ReturnUrl = returnUrl;
        //    return View(model);
        //}

        [HttpPost]
        public ActionResult ZewnetrzneLogowanie(string provider)
        {
            // Request a redirect to the external login provider
            return new ChallengeResult(provider, Url.Action("ZewnetrzneLogowanieCallback"));
        }

        public async Task<ActionResult> ZewnetrzneLogowanieCallback()
        {
            var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync();
            if (loginInfo == null)
            {
                return RedirectToAction("Zaloguj");
            }


            var result = new ApplicationSignInManager(HttpContext.GetOwinContext()).LogowanieZewnetrzne(loginInfo.DefaultUserName);

            switch (result)
            {
                case SignInStatus.Success:
                    var tokenExpiration = TimeSpan.FromDays(1);
                    ClaimsIdentity identity = new ClaimsIdentity(OAuthDefaults.AuthenticationType);
                    identity.AddClaim(new Claim(ClaimTypes.Name, loginInfo.DefaultUserName));
                    var props = new AuthenticationProperties()
                    {
                        IssuedUtc = DateTime.UtcNow,
                        ExpiresUtc = DateTime.UtcNow.Add(tokenExpiration),
                    };
                    var ticket = new AuthenticationTicket(identity, props);

SerwisOgloszen/Views/Uzytkownik/Edytuj.cshtml
@using SerwisOgloszen.BazaDanych
@using SerwisOgloszen.Models
@model EdytujViewModel


<h2>Edytuj - @Model.Login</h2>


@using (Html.BeginForm("Edytuj", "Uzytkownik", FormMethod.Post))
{
    @Html.HiddenFor(x=>x.Id)
    <div class="row">
        <div class="col-sm-5 col-md-3">
            <div class="form-group">
                @Html.LabelFor(x => x.Haslo)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                    @Html.PasswordFor(x => x.Haslo, new
               {
                   @class = "form-control",
                   placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.Haslo).ToHtmlString())
               })
                </div>
                @Html.ValidationMessageFor(x => x.Haslo)
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-5 col-md-3">
            <div class="form-group ">
                @Html.LabelFor(x => x.PowtorzoneHaslo)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                    @Html.PasswordFor(x => x.PowtorzoneHaslo, new
               {
                   @class = "form-control",
                   placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.PowtorzoneHaslo).ToHtmlString())
               })
                </div>
                @Html.ValidationMessageFor(x => x.PowtorzoneHaslo)
            </div>
        </div>
    </div>
 <div class="row">
     <div class="col-sm-2 col-md-2">
         <div class="form-group">
             @Html.LabelFor(x=>x.Rola)
             @Html.DropDownListFor(x=>x.Rola,Model.ListaRol,new { @class = "form-control" })
         </div>
     </div>
 </div>
    <button class="btn btn-default">Edytuj</button>
    <button class="btn btn-default">Anuluj</button>

}

SerwisOgloszen/Views/Uzytkownik/ListaUzytkownikow.cshtml
@using SerwisOgloszen.BazaDanych
@model  List<Uzytkownik>
@using SerwisOgloszen.Enums

<script>

    $(document).ready(function () {
        $('.btn-usun').click(function () {
            var btn = $(this);

            swal({
                title: 'Na pewno chcesz go usunąć?',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Tak,chcę go usunąć!',
                cancelButtonText: 'Anuluj'
            }).then(function () {
                $(btn).closest('form').submit();
            })
        });

    });

</script>

<h2>Lista użytkowników</h2>

<div class="row">
    <div class="col-sm-12">
        <table class="table table-striped">
            <tr>
                <th>
                    Login
                </th>
                <th>
                    Rola
                </th>
                <th></th>
                <th></th>
            </tr>
            @foreach (Uzytkownik uzytkownik in Model)
            {
                <tr>
                    <td>
                        @uzytkownik.Login
                    </td>
                    <td>
                        @((RolaUzytkownika)uzytkownik.Rola)
                    </td>
                    <td>
                        @using (Html.BeginForm("Usun", "Uzytkownik", FormMethod.Post))
                        {
                            @Html.Hidden("id", uzytkownik.Id)  @*nazwa ma byc tak jak nazwa parametru w kontrolerze , a wartosc pobieramy z konkretnego elementu modelu*@
                            <button type="button" class="glyphicon glyphicon-trash btn-usun"></button>
                        }
                    </td>

                    <td>
                        @using (Html.BeginForm("Edytuj", "Uzytkownik", FormMethod.Get))
                        {
                            @Html.Hidden("id", uzytkownik.Id)
                            <button class="glyphicon glyphicon-cog"></button>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

SerwisOgloszen/Views/Uzytkownik/Logowanie.cshtml
@using SerwisOgloszen.Models
@model LogowanieViewModel
@{
    ViewBag.Title = "Logowanie";
}

<h2>Logowanie</h2>

@using (Html.BeginForm("Zaloguj", "Uzytkownik", FormMethod.Post))
{
    <div class="row">
        @*klasa do wierszy (dane elementy sa w nowej lini )*@
        <div class="col-sm-5 col-md-3">
            @*klasa col w zaleznosci czy sm czy md (sugeruje wielkosc wyswietlacza uzytkownika) dostosowuje aplikacje do wielkosci*@
            <div class="form-group">
                @*@Html.Label("Login")*@  @*wyswietle tekstu login w tagu label*@
                @Html.LabelFor(x => x.Login) @*to jest to samo co label zwykly tylko ze pobiera nazwe pola z modelu*@
                <div class="input-group">
                    @*ta klasa daje szare pole w text box*@
                    <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div> @*ten span sluzy do dodana ikonki  a div to jest moje szare pole w tex box*@
                    @Html.TextBoxFor(x => x.Login, new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.Login) }) @*placeholder
                        sluzy do pobrania nazwy pola do tex box*@
                </div>
                @Html.ValidationMessageFor(x => x.Login)  @*bez tego nie pojawi sie komunikat ktory napisalismy w viewModel nad polem*@
            </div>

        </div>
    </div>

    <div class="row">
        <div class="col-sm-5 col-md-3">
            <div class="form-group">
                @Html.LabelFor(x => x.Haslo)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                    @Html.PasswordFor(x => x.Haslo, new
               {
                   @class = "form-control",
                   placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.Haslo).ToHtmlString())
               })
                </div>
                @Html.ValidationMessageFor(x => x.Haslo)
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-5 col-md-3">
            @Html.CheckBoxFor(x => x.ZapamietajMnie)
            @Html.LabelFor(x => x.ZapamietajMnie)
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <button class="btn btn-default">Zaloguj</button>
        </div>
    </div>
}
<div class=" row">
    <div class="col-sm-5 col-md-3">
        @Html.Partial("_ZewnetrznePortaleDoLogowania")
    </div>
</div>

SerwisOgloszen/Views/Uzytkownik/Rejestracja.cshtml
@using SerwisOgloszen.Models
@model RejestracjaViewModel
@*sluzy do korzystania z pol w modelu i do zdefiniowania typu widoku*@

<h2>Rejestracja</h2>

@using (Html.BeginForm("Zarejestruj", "Uzytkownik", FormMethod.Post))
{
    <div class="row">
        <div class="col-sm-5 col-md-3">
            <div class="form-group">
                @Html.LabelFor(x => x.Login)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                    @Html.TextBoxFor(x => x.Login, new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.Login) })
                </div>
                @Html.ValidationMessageFor(x => x.Login)
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-5 col-md-3">
            <div class="form-group ">
                @Html.LabelFor(x => x.Haslo)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                    @Html.PasswordFor(x => x.Haslo, new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.Haslo) })
                </div>
                @Html.ValidationMessageFor(x => x.Haslo)
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-5 col-md-3">
            <div class="form-group ">
                @Html.LabelFor(x => x.PowtorzoneHaslo)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                    @Html.PasswordFor(x => x.PowtorzoneHaslo, new
               {
                   @class = "form-control",
                   placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.PowtorzoneHaslo).ToHtmlString())
               })
                </div>
                @Html.ValidationMessageFor(x => x.PowtorzoneHaslo)
            </div>
        </div>
    </div>

    <button class="btn btn-default">Rejestracja</button>





}

SerwisOgloszen/Views/Uzytkownik/_ZewnetrznePortaleDoLogowania.cshtml
@using Microsoft.Owin.Security

<hr />
@{
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();

    using (Html.BeginForm("ZewnetrzneLogowanie", "Uzytkownik"))
    {
        <div id="socialLoginList">
            <p>
                @foreach (AuthenticationDescription p in loginProviders)
                {
                    <button type="submit" class="btn btn-default" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType" title="Log in using your @p.Caption account">@p.AuthenticationType</button>
                }
            </p>
        </div>
    }
}